pizzaWeb/menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'

urlpatterns = [
    path('', views.index, name="index"),
]

pizzaWeb/pizzaWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', include('menu.urls')),
]

pizzaWeb/menu/models.py
from django.db import models


class Pizza(models.Model):
    nom = models.CharField(max_length=120)
    ingredients = models.CharField(max_length=400)
    prix = models.FloatField(default=0)
    vegetarienne = models.BooleanField(default=False)

    def __str__(self):
        return self.nom

pizzaWeb/menu/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Pizza


# Create your views here.

# EXERCICE
# Les pizzas : Végétarienne : 8.5€, Poulet champignons : xxx, 4 fromages, Carnivore


def index(request):
    pizzas = Pizza.objects.all().order_by('prix')
    return render(request, 'menu/index.html', {'pizzas': pizzas})

pizzaWeb/menu/templates/menu/index.html
{% load static %}

<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Menu des pizzas</title>
    <link rel="stylesheet" href="{% static 'menu/style.css' %}">
</head>
<body>

    <a href="{% url 'menu:index' %}"><img id="small_logo" src="{% static 'menu/images/small_logo.png' %}"></a>

    <div class="menu_title">
        <h1>Menu Pizza's</h1>
    </div>

    <div class="menu_list">
        {% for pizza in pizzas %}
        <div class="menu_list_item">
            <span class="menu_list_title">{{pizza.nom}}</span>
            <span class="menu_list_prix">{{pizza.prix | floatformat:2}}€</span>
            <span class="menu_list_ingredients">{{pizza.ingredients}}</span>
            {% if pizza.vegetarienne %}
                <span class="menu_list_badge">VÉGÉTARIENNE</span>
            {% endif %}
        </div>
        {% endfor %}
    </div>
</body>
</html>